# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('skuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('listDate', models.CharField(max_length=20)),
                ('inputType', models.CharField(max_length=20)),
                ('isSmart', models.CharField(max_length=10)),
                ('osVersion', models.CharField(max_length=40)),
                ('mbROM', models.CharField(max_length=100)),
                ('scrSize', models.CharField(max_length=15)),
                ('fenbianlv', models.CharField(max_length=40)),
                ('hvGPS', models.CharField(max_length=10)),
                ('reCamera', models.CharField(max_length=15)),
                ('prCamera', models.CharField(max_length=15)),
                ('hvWiFi', models.CharField(max_length=10)),
                ('hvBlue', models.CharField(max_length=10)),
                ('battery', models.CharField(max_length=60)),
                ('mbSize', models.CharField(max_length=40)),
                ('mbWeight', models.CharField(max_length=40)),
            ],
        ),
    ]
