# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='battery',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='fenbianlv',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='inputType',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='listDate',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='mbSize',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='mbWeight',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='osVersion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='prCamera',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='reCamera',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='scrSize',
            field=models.CharField(max_length=200),
        ),
    ]
